apiVersion: v1
kind: Service
metadata:
  name: {{ include "roost-keeper.metricsServiceName" . }}
  namespace: {{ include "roost-keeper.namespace" . }}
  labels:
    {{- include "roost-keeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.networking.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.networking.metricsService.type }}
  {{- if .Values.networking.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.networking.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.networking.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  - name: https
    port: {{ .Values.networking.metricsService.port }}
    protocol: TCP
    targetPort: {{ .Values.networking.metricsService.targetPort }}
  selector:
    {{- include "roost-keeper.controllerSelectorLabels" . | nindent 4 }}
---
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "roost-keeper.webhookServiceName" . }}
  namespace: {{ include "roost-keeper.namespace" . }}
  labels:
    {{- include "roost-keeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  {{- with .Values.networking.webhookService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.networking.webhookService.type }}
  {{- if .Values.networking.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.networking.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: webhook
    port: {{ .Values.networking.webhookService.port }}
    protocol: TCP
    targetPort: {{ .Values.networking.webhookService.targetPort }}
  selector:
    {{- include "roost-keeper.controllerSelectorLabels" . | nindent 4 }}
{{- end }}
