{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roost-keeper.serviceAccountName" . }}
  namespace: {{ include "roost-keeper.namespace" . }}
  labels:
    {{- include "roost-keeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
